// Generated by CoffeeScript 1.6.3
var AppView, Index, UniversalSlider, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AppView = require('app/views/app_view');

UniversalSlider = require('app/components/universal_slider');

module.exports = Index = (function(_super) {
  __extends(Index, _super);

  function Index() {
    this.resize = __bind(this.resize, this);
    _ref = Index.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Index.prototype.after_render = function() {
    var _this = this;
    console.log("index");
    this.slider = new UniversalSlider({
      el: $("#slider"),
      width: 500,
      height: 227,
      images: ["/images/home_slider1.png", "/images/home_slider2.png", "/images/home_slider3.png"]
    });
    $("#prev").on("click", function() {
      return _this.slider.prev();
    });
    $("#next").on("click", function() {
      return _this.slider.next();
    });
    return $(window).on("resize", this.resize);
  };

  Index.prototype.resize = function() {
    return this.slider.resize(600, 300);
  };

  return Index;

})(AppView);
